### ISSUE TITLE
Issues with probing.

### ISSUE THREAD

**Issue by Zchulski** [Dendrowen/Blobifier#33]
The shaker arms is too big for the Voron tap, at least for mine.  the X axis parts hit the shaker arm and throw off tap when probing the bed

**Comment by Dendrowen** [comment]
I had no issues with voron Tap on this, but changing the QGL locations more inward might help. I don't really have any other solution because the arm needs to be able to reach the toolhead.

**Comment by Strangehadron** [comment]
Hi,
Just install a blobifier and I have the same issue with a tap (the printed one by voron team)

**Hardware**: Voron 2.4 300, with 305mm stock bed, (8mm M4 knurled nuts spacer for mounting bed), Voron tap (printed)

**Problems** :
- Bottom of left XY joint crash in shaker arm when probing (QGL on rear).
- Worse, I have also my rear left Z motor crashing in the wall of the bucket when probing. (Z motors are moons from formbot)


Video when QGL:
https://github.com/user-attachments/assets/bb80e926-940e-4f52-9515-64b499ab2653

Motor position (i had already cut a little part on the wall of the bucket on this picture):
![IMG_1766](https://github.com/user-attachments/assets/0164a69c-ce3c-4505-ad8d-0b2ee3900fb1)


- For the bucket I have with my very poor cad skills made a modification of the rear wall of the bucket to avoid crashing my motor on it.
![IMG_1773](https://github.com/user-attachments/assets/7edddca3-f8cd-4273-abd8-75a5bb25e3ff)

- For the shaker, i’m going to try to raise my bed by a few mm with spacer to avoid bottom of left xy joint touching shaker arm.

A contributor of voron discord (fboc, thanks to him) looked the 2.4 and blobifier cad and said that with a spacer (M4 knurled nuts) for the bed less than 8.5mm the bottom screw (the bhcs one) of left xy joint is going to touch the shaker arm.
https://discord.com/channels/460117602945990666/500407802414628876/1306742829636128778

It make sense with the tap since the toolhead go lower than other popular probing solution.
